### ISSUE TITLE
diceware_word_list_it-IT under GPL v3

### ISSUE THREAD

**Issue by taringamberini** [akheron/diceware.py#6]
Hi Petri,

I have recently released the [diceware_word_list_it-IT](https://github.com/taringamberini/diceware_word_list_it-IT/tree/master/diceware/wordlist) under GPL v3: a more suitable license when diceware_word_list_it-IT is used as part of software.

Please consider changing to GPL v3. If you didn't change there would be no problem to me :-)

Thanks,
Tarin

**Comment by akheron** [comment]
I changed the it language list to use your list, but I don't see a reason to switch to GPLv3.

**Comment by taringamberini** [comment]
> but I don't see a reason to switch to GPLv3.

It seams to me that your `.py` files are [Expat License](http://www.gnu.org/licenses/license-list.en.html#Expat) licensed.

Accordingly to [compatibility license list](https://www.gnu.org/licenses/quick-guide-gplv3.html#new-compatible-licenses) the "MIT License" (both"Expat License" and "X11 License") you have applied to your code is GPL v2 or GPL v3 compatible, but the language list you have previously used is [GFDL licensed that is GPL incompatible](http://en.wikipedia.org/wiki/GNU_Free_Documentation_License#GPL_incompatible_in_both_directions).

To overcame this incompatibility issue I have released the diceware_word_list_it-IT under both GFDL (to be used as documentation) and GPL (to be used in code).

Hi,
Tarin
